import type { Metadata } from "next";
import { Inter } from "next/font/google";
import "./globals.css";
import { initResourceFromURL } from "@/lib/startup/initResources";

const inter = Inter({ subsets: ["latin"] });

initResourceFromURL().catch(console.error);

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body className={inter.className}>
        <main>{children}</main>
      </body>
    </html>
  );
}
